class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
  	self.new(
  		provider: auth_hash["provider"], # the authorization provider in string
  		uid: auth_hash["uid"], # string generated by the provider that uniquely identifies a user
  		token: auth_hash["credentials"]["token"] # access token by provider after successful authentication by provider in string
  	)
  end

  def update_token(auth_hash)
  	self.token = auth_hash["credentials"]["token"]
  	self.save
  end
end
